blank_issues_enabled: false
contact_links:
  - name: 讨论区
    url: https://github.com/HelloWRC/ClassIsland/discussions/
    about: 使用中若遇到问题或有新点子新需求，请先在这里求助和征求意见。
  - name: 加入QQ群
    url: https://qm.qq.com/q/4NsDQKiAuQ
    about: 在QQ群和开发者以及其它用户交流讨论。