name: 功能请求
description: 提出一项新的功能。
title: "[功能请求]: 在这里输入你的标题"
labels: ["enhancement"]
assignees: HelloWRC
body:
  - type: markdown
    attributes:
      value: |
        感谢您贡献您的想法。请在上面的文本框⬆️起一个能够清晰描述您的想法的标题，便于开发者了解您的想法。**不要删掉开头的“[功能请求]: ”。**

        > **重要：如果您想要提出多项功能，请为每一个功能开一个单独的issue**
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 在开始之前，请先检查：
      options:
        - label: 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
          required: true
        - label: 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
          required: true
        - label: 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。
          required: true
  - type: textarea
    id: back
    attributes:
      label: 背景与动机
      description: 添加此功能的理由。
    validations:
      required: true
  - type: textarea
    id: req
    attributes:
      label: 想要实现或优化的功能
      description: 详细地描述一下你想要的功能，描述的越具体，采纳的可能性越高。
    validations:
      required: true
